#!/bin/sh
#
# wget-mirror - command to mirror a site

# get version
#
VERSION='$Revision: 1.2 $'
VERSION=`/bin/echo "$VERSION" | /bin/sed -e 's/^.*: //' -e 's/ .*$//'`

# parse args
#
if [ $# -lt 2 ]; then
    echo "usage: $0 http://www.some.url local_dir [other wget -flags ...]" 1>&2
    exit 1
fi
URL="$1"
DIR="$2"
shift
shift

# firewall
#
if [ ! -d "$DIR" ]; then
    mkdir -p "$DIR" 2>/dev/null
fi
if [ ! -d "$DIR" ]; then
    echo "$0: cannot create directory: $DIR" 1>&2
    exit 2
fi
cd "$DIR"

# NOTE: -q	==>	--quiet
#	-m	==>	--mirror
#	-nH	==>	--no-host-directories
#	-p	==>	--page-requisites
#	-U x	==>	--user-agent=x
#	-l num	==>	--level=num	(-l 0 means infinite)
#	-t num	==>	--tries=num
#	-np	==>	--no-parent
#	-L	==>	--relative
#
# NOTE: use --limit-rate=20k for 20k/sec rage limit
#	    --limit-rate=inf for max (unlimited) rate (default is unlimited)
#	use --level=32 to limit recursion to a sane level (default is 5)
#	    --level=inf (or --level=0) for infinite recursion
#	use --quiet to reduce output for something like a cron job
#
wget --mirror --user-agent=wget-mirror-$VERSION \
     --no-host-directories \
     --page-requisites --no-parent --relative \
     --level=20 --tries=20 \
     $@ "$URL"
